version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.17
    - 7.13.14
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.13
  - dependency-name: chai
    versions:
    - 4.3.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.5

